### ISSUE TITLE
Registering an op twice from Python raises an exception

### ISSUE THREAD

**Issue by willcrichton** [scanner-research/scanner#109]
This isn't necessarily a bug, but it currently manifests as one. For example, `pipelines.detect_faces` registers a `BBoxNMS` kernel every time it's called, which means multiple calls to `pipelines.detect_faces` will fail after the first. There are a few options here:

1. Have some form of checking if a kernel is registered, and add that check everywhere in the current examples that use kernel registration. 
2. Don't raise an exception, just print a warning.
3. Instead of adding an explicit check, just catch the ScannerException.

What do you think @apoms?

**Comment by apoms** [comment]
The two scenarios we want to differentiate between is:

1) Two Ops/Kernels registering with the same name but with different implementations
2) Re-registering the same Op/Kernel

The first should definitely be an error, but the latter is fine (maybe just a warning). This basically only comes up in the case of Python kernels (since C++ kernels are registered at file scope) so a Python specific solution should be ok.

Two solutions:

- Unregister kernels. In the case of the detect pipeline, we would just unregister the kernel after use and then reregister it again when we need it.
- Temporary Kernels. Instead of registering kernels, we can provide a way to have a 'temporary' kernel which only exists for the pipeline it is defined in, and not part of the 'registry'. This is more complex but means we don't have the issue of dealing with registered kernel state.

**Comment by willcrichton** [comment]
TODO: have kernel registrations in Python stdlib check if op is registered first

**Comment by apoms** [comment]
I haven't seen this issue anymore. I think this was resolved by making python kernels "Temporary", in that they are suffixed with a UUID generated once per python process and thus unique across client sessions.
