### ISSUE TITLE
Openpose with GPU

### ISSUE THREAD

**Issue by PushyamiKaveti** [scanner-research/scanner#221]
Hi,
I am trying to use openpose with scanner.Though I could run openpose and extract poses it seems like the GPUs are not being used to the full potential. On the other hand if I set the devicetype to CPU its reasonable faster. However, the poses are not being drawn i.e drawpose() function is not called. I  gave some print statements inside drawpose() to check this.  Is there a way to specify the number of GPUs to use? am I doing anything wrong here? 

Thanks,
Pushyami

**Comment by apoms** [comment]
Hi,

Can you be a bit more specific by "the gpus are not being used to the full potential"? For example:

- How are you measuring utilization? 
- What performance do you expect to see?
- Which GPUs are you using and how many?

What do you mean by 'the poses are not being drawn'? Does the output video not show poses drawn on the video? It's possible there are no poses being detected and thus there is nothing to draw.

By default, Scanner will use all the GPUs on your machine. You can specify the number of GPUs to use by setting the `pipeline_instances` variable on line 42 in the pose_detection app.

Alex

**Comment by willcrichton** [comment]
Hi, it's possible that the CPU implementation of OpenPose isn't working properly. We haven't tested it heavily, since they only recently adopted CPU support. I suspect it seems fast since it's not actually doing anything.

With respect to GPU utilization: I wouldn't use GPU memory as the metric for utilization. There are plenty of networks like OpenPose that only need 3-4 GB of memory. You should look at the % compute utilization (also shown in `nvidia-smi`), and get a sense of what the average utilization is. The closer to 100, the better.

**Comment by willcrichton** [comment]
@PushyamiKaveti I'm going to close this for now, but feel free to reopen it if you think the perf is still an issue.
