### ISSUE TITLE
Uniform parameters for tables/samples

### ISSUE THREAD

**Issue by willcrichton** [scanner-research/scanner#7]
Useful to have some way of exposing uniform parameters. For example, astro application has telescope parameters (PSF) common to all images. Could also be used to replace the "frame_info" column with uniform parameters for each video.

**Comment by apoms** [comment]
Agreed. It's also important for calibration parameters between cameras in 3d reconstruction applications. 

One reason we may not want to replace frame_info is because it would force kernels to deal with the scenario where consecutive images are or varying size. For example, if we want to support image collections. 

Also, at some point we will end up replicating most of the data management provided by existing databases. Perhaps there's a way to just leverage those?
