### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [scanner-research/scanner#76]
Hi Will & Alex,

I have been closely following development of Scanner and had few questions after going through [1]

1. Is scanner limited to H.264 encoding or can it work with say VP9 etc.  

2. Are / Can the intermediate tables stored on disk using LMDB or LevelDB etc. I see that it might not be compatible with current Storehouse architecture which is FS agnostic. [2]  

3. Is it possible to ingest videos in-place? E.g. By mmaping the original files and storing only metadata byte offsets / GOP information in leveldb or lmdb format. This will reduce storage use by a factor of two. 

[1]  http://platformlab.stanford.edu/Seminar%20Talks/Will_Crichton.pdf  

[2] https://github.com/scanner-research/scanner/blob/master/scanner/api/database.h

Thanks,
Akshay

**Comment by apoms** [comment]
Hi Akshay,

1. Scanner is designed to support any video format which has a structure similar to Group of Pictures (GOP)/keyframes. We currently only implement support for H.264 encoded video, but I believe it would be fairly straightforward to add support for other codecs. H.264 is appealing due to widespread hardware support, especially in modern GPUs. 

2. Not currently, though it would be great to support custom storage formats as an extension to the system (this is related to point 3 since you'd like to work with existing data). Part of the design of Scanner is that users of the system can write applications which are agnostic of the storage representation, easing some of the burden of data management.

3. Yes, this is definitely something we are interested in and have talked about doing for a while. We currently do some minor pre-processing (just changing the packet format of the compressed bytestream) that we would not be able to do for in-place video, but I believe that could be done on the fly with very little overhead.

Thanks for the questions!

Alex

**Comment by AKSHAYUBHAT** [comment]
Thanks for the quick response, It seems to me that Scanner is perfect for an end-to-end (Decode -> Sample/Stride -> Resize -> Compute) pipeline, e.g. for the pose task from multi-camera setup in the slides. But if you can store an intermediate representation, say after sample into something say a locked lmdb database it could be used by any consumer process e.g. TensorFlow etc.

Finally it might be interesting to look at how much GPU decode really helps for deep learning tasks. When using Caffe ops, my guess is that the true rate limiting step is the Caffe/Inference. And it might be useful to just decode on CPU and fill the queue while keeping GPU solely for Caffe. 
 
Best,
Akshay

**Comment by apoms** [comment]
Agreed, having a more tightly integrated story for data export would make it easier to integrate with other tools. I think the required additions for that are: 
1. Support in-place data
2. Custom data formats, both for loading and saving
3. Specify how and where data should be exported in the pipeline description

As for DL tasks, it really depends on the network. For classification tasks, the network is almost never the bottleneck (GoogLeNet and kind can achieve thousands of FPS while decode is around 700-1000 FPS if using hardware correctly). For detection type tasks, most popular network designs are extremely computationally intensive and usually dominate the pipeline. However, there is a lot of work being done to slim networks down and I expect that the current regime of networks that can only run at 10-30 FPS on a Titan X will not last forever. In that case, the other parts of the pipeline, such as decode, will matter.

**Comment by AKSHAYUBHAT** [comment]
Hi, I recently incorporated some of the ideas from Scanner (specifically splitting at I-type keyframes), into Deep Video Analytics. This was straightforward since ffmpeg provides a "segment" muxer that splits videos into chunks. While its difficult to ensure exactly one GOP per segment, but by setting a very low value of segment_times you can get small chunks (1~4 GOPs). Further since each segment is stored as a separate mp4 file it can be used directly for streaming video.
